add workflow diagrams
Idea-Pool/js-assertion-cheat-sheet pull request #14
Opened 2024-05-06 13:59 UTC by kornel-filep

## What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)
Adds docs on the planned deployment workflows

## What is the current behavior? (You can also link to an open issue here)
-
## What is the new behavior (if this is a feature change)?
-
## Does this PR introduce a breaking change? (What changes might users need to make in their application due to this PR?)
-
## Other information:
-

2024-05-08 06:05 UTC, szikszail commented
@kornel-filep please add the drawio files as well so that later they can be edited if needed

2024-05-08 06:06 UTC, szikszail requested changes
~~@kornel-filep please add the drawio files as well so that later they can be edited if needed~~

2024-05-08 06:12 UTC, szikszail requested changes
Please ignore the previous comment, I just found it.
Could you please create a markdown file describing the CI/CD workflow?

2024-05-15 06:34 UTC, kornel-filep commented
> Please ignore the previous comment, I just found it. Could you please create a markdown file describing the CI/CD workflow?

I have added a description to the diagrams. Please let me know if I missed anything, or if I should write down in more detail.

2024-05-15 06:48 UTC, szikszail submitted a review, later dismissed

2024-05-25 18:56 UTC, taughty reviewed
You might want to fix some incorrect casing in source files, i.e.:
- _Github Actions_ -> _GitHub Actions_
- _Github pages_ -> _GitHub Pages_
- _Cloudfront_ -> _CloudFront_

2024-05-25 18:56 UTC, taughty commented on .github/docs/branch-deploy.drawio.png
Artifacts seem to be inconsistent, i.e. `build` job archives _application build artifacts_ and `deploy` job downloads _application artifact_. Also, in the *Archived artifacts* box it is referred to as _site_.

2024-05-25 18:56 UTC, taughty commented on .github/docs/main-deploy.drawio.png
Artifacts seem to be inconsistent, i.e. `build` job uploads _Pages artifacts_ and `deploy` job downloads _application artifact_.

2024-05-25 18:56 UTC, taughty commented on .github/docs/stack-deploy.drawio.png
Is this pipeline going to use the _CDK Output JSON_ archieved by the `stack-deploy` pipeline? In this case you might want to add it in a box under the _GitHub Environment variables_ the same way as on the `stack-deploy` diagram.

2024-05-27 10:52 UTC, kornel-filep commented on .github/docs/stack-deploy.drawio.png
No, this pipeline should not use the output JSON file.
We archive it just as an output of the CDK execution, the necessary stuff is saved to new variables for the environment, like `AWS_BUCKET_NAME`.

2024-05-27 11:00 UTC, kornel-filep commented
@taughty addressed your comments with a new commit. Please take a look and resolve if suitable.

2024-05-27 11:10 UTC, szikszail approved these changes

2024-05-28 09:39 UTC, taughty approved these changes

2024-05-28 09:39 UTC, merged